# Generated by Django 5.2.7 on 2025-10-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField(default=1)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('toys', 'Toys'), ('mobiles', 'Mobiles'), ('laptops', 'Laptops'), ('accessories', 'Accessories'), ('other', 'Other')], default='', max_length=50)),
                ('description', models.TextField(default='', null=True)),
                ('excerpt', models.CharField(default='', max_length=150)),
                ('tags', models.ManyToManyField(to='products.tag')),
            ],
        ),
    ]
