# Generated by Django 5.2.7 on 2025-10-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_storeuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='seller', max_length=50),
        ),
    ]
