# Generated by Django 5.2.7 on 2025-10-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storeuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=50),
        ),
    ]
